# Generated by Django 5.2.7 on 2025-11-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_merge_20250717_2256"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviciocliente",
            name="configuracion",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="serviciocliente",
            name="estado",
            field=models.CharField(
                choices=[
                    ("activo", "Activo"),
                    ("suspendido", "Suspendido"),
                    ("finalizado", "Finalizado"),
                ],
                default="activo",
                max_length=20,
            ),
        ),
    ]
