# Generated by Django 5.2.7 on 2025-11-21 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("api", "0008_serviciocliente_configuracion_serviciocliente_estado"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoriaGasto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                ("descripcion", models.TextField(blank=True, default="")),
                (
                    "limite_monto",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Límite opcional por ítem en la categoría",
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cliente_servicio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categorias_gasto",
                        to="api.serviciocliente",
                    ),
                ),
            ],
            options={
                "ordering": ["nombre"],
                "unique_together": {("cliente_servicio", "nombre")},
            },
        ),
        migrations.CreateModel(
            name="ReporteGasto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador"),
                            ("en_revision", "En revisión"),
                            ("aprobado", "Aprobado"),
                            ("rechazado", "Rechazado"),
                        ],
                        default="borrador",
                        max_length=20,
                    ),
                ),
                (
                    "monto_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "moneda",
                    models.CharField(
                        choices=[("UF", "UF"), ("USD", "USD"), ("CLP", "CLP")],
                        default="CLP",
                        max_length=10,
                    ),
                ),
                ("fecha_envio", models.DateTimeField(blank=True, null=True)),
                ("comentario", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cliente_servicio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reportes_gasto",
                        to="api.serviciocliente",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ItemGasto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "moneda",
                    models.CharField(
                        choices=[("UF", "UF"), ("USD", "USD"), ("CLP", "CLP")],
                        default="CLP",
                        max_length=10,
                    ),
                ),
                ("fecha", models.DateField()),
                ("descripcion", models.TextField(blank=True, default="")),
                (
                    "adjunto",
                    models.FileField(
                        blank=True, null=True, upload_to="rindegastos/adjuntos/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="items",
                        to="rindegastos.categoriagasto",
                    ),
                ),
                (
                    "reporte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="rindegastos.reportegasto",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EventoRindeGastos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "accion",
                    models.CharField(
                        choices=[
                            ("enviar", "Enviar"),
                            ("aprobar", "Aprobar"),
                            ("rechazar", "Rechazar"),
                            ("actualizar", "Actualizar"),
                        ],
                        max_length=20,
                    ),
                ),
                ("comentario", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reporte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eventos",
                        to="rindegastos.reportegasto",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CentroCosto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                ("codigo", models.CharField(blank=True, default="", max_length=50)),
                ("activo", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cliente_servicio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="centros_costo",
                        to="api.serviciocliente",
                    ),
                ),
            ],
            options={
                "ordering": ["nombre"],
                "unique_together": {("cliente_servicio", "nombre")},
            },
        ),
    ]
