# Generated by Django 5.2.7 on 2025-11-21 16:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_seed_rindegastos_servicio"),
        ("rindegastos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="centrocosto",
            options={"ordering": ["apodo"]},
        ),
        migrations.RenameField(
            model_name="centrocosto",
            old_name="nombre",
            new_name="apodo",
        ),
        migrations.AlterUniqueTogether(
            name="centrocosto",
            unique_together={("cliente_servicio", "apodo")},
        ),
        migrations.CreateModel(
            name="Rendicion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_ejecucion",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("datos_archivo", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cliente_servicio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rendiciones",
                        to="api.serviciocliente",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_ejecucion"],
            },
        ),
        migrations.CreateModel(
            name="CuentaGlobal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=50)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("IVA", "IVA"),
                            ("GASTO", "Gasto"),
                            ("PROVEEDOR", "Proveedores"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cliente_servicio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cuentas_globales",
                        to="api.serviciocliente",
                    ),
                ),
            ],
            options={
                "ordering": ["codigo"],
                "unique_together": {("cliente_servicio", "codigo")},
            },
        ),
        migrations.CreateModel(
            name="TipoDocumento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=30)),
                ("nombre", models.CharField(max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cliente_servicio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tipos_documento",
                        to="api.serviciocliente",
                    ),
                ),
            ],
            options={
                "ordering": ["nombre"],
                "unique_together": {("cliente_servicio", "codigo")},
            },
        ),
    ]
