# Generated by Django 5.2.7 on 2025-11-21 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rindegastos", "0002_alter_centrocosto_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="itemgasto",
            name="categoria",
        ),
        migrations.RemoveField(
            model_name="eventorindegastos",
            name="reporte",
        ),
        migrations.RemoveField(
            model_name="eventorindegastos",
            name="usuario",
        ),
        migrations.RemoveField(
            model_name="itemgasto",
            name="reporte",
        ),
        migrations.RemoveField(
            model_name="reportegasto",
            name="cliente_servicio",
        ),
        migrations.RemoveField(
            model_name="reportegasto",
            name="usuario",
        ),
        migrations.DeleteModel(
            name="CategoriaGasto",
        ),
        migrations.DeleteModel(
            name="EventoRindeGastos",
        ),
        migrations.DeleteModel(
            name="ItemGasto",
        ),
        migrations.DeleteModel(
            name="ReporteGasto",
        ),
    ]
