# Generated by Django 5.2.7 on 2025-11-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rindegastos', '0003_remove_itemgasto_categoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RendicionMovimiento',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Movimiento de rendición',
                'verbose_name_plural': 'Movimientos de rendición',
                'db_table': 'rindegastos_rendicionmovimiento',
                'ordering': ['-id'],
                'managed': False,
            },
        ),
    ]
