# Generated by Django 5.2.7 on 2025-11-25 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rindegastos', '0004_rendicionmovimiento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RendicionMovimiento',
        ),
    ]
